### ISSUE TITLE
好像无效

### ISSUE THREAD

**Issue by huoyan1231** [scgm0/BetterChinese#1]
EMTK控制台输出：

8.12.2024 19:08:45 [Client Error] EMTK: Exception thrown when early loading BetterChinese, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.NotImplementedException: The method or operation is not implemented.
at Vintagestory.Client.Gui.MainMenuAPI.StoreModConfig[T](T jsonSerializeableData, String filename) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\API\MainMenuAPI.cs:line 267
at BetterChinese.BetterChineseModSystem.LoadConfig(ICoreAPI api, String modId) in /home/scgm/RiderProjects/BetterChinese/BetterChinese/BetterChineseModSystem.cs:line 34
at BetterChinese.BetterChineseModSystem.EarlyLoad(ModContainer mod, ScreenManager sm) in /home/scgm/RiderProjects/BetterChinese/BetterChinese/BetterChineseModSystem.cs:line 41
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of inner exception stack trace ---
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
at EMTK.EMTK.EarlyLoadMods(Boolean reload) in /home/mgz/Documents/Code/git/vintagemods/Early Mod Toolkit 3/src/EMTK.cs:line 191, InnerException: System.NotImplementedException: The method or operation is not implemented.
at Vintagestory.Client.Gui.MainMenuAPI.StoreModConfig[T](T jsonSerializeableData, String filename) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\MainMenu\API\MainMenuAPI.cs:line 267
at BetterChinese.BetterChineseModSystem.LoadConfig(ICoreAPI api, String modId) in /home/scgm/RiderProjects/BetterChinese/BetterChinese/BetterChineseModSystem.cs:line 34
at BetterChinese.BetterChineseModSystem.EarlyLoad(ModContainer mod, ScreenManager sm) in /home/scgm/RiderProjects/BetterChinese/BetterChinese/BetterChineseModSystem.cs:line 41
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr).

**Comment by scgm0** [comment]
尝试一下最新的0.1.2？

**Comment by huoyan1231** [comment]
> 尝试一下最新的0.1.2？

正常了，感谢
